### PR TITLE
Add support for `AENSv2.pointee`, `AENSv2.name` types

### LINKED ISSUE #210: Support AENSPointee from Ceres
As I understood from https://github.com/aeternity/aeternity/pull/4056 there has been added a new variant to

https://github.com/aeternity/aepp-calldata-js/blob/410effa3c6ded41baaf2ea18619c5af4a982cf6d/src/FateTypes.js#L172-L181

If I'm trying to pass AENSPointee to contract call using the current version of calldata on Ceres if fails with `bad_pointer`, I assume it is because mismatch of variants size.

Calldata needs to support both Iris and Ceres (the same as js sdk) to allow smooth migration.

### PR DESCRIPTION
**Pull request by davidyuk**
depends on https://github.com/aeternity/aepp-calldata-js/pull/258

closes #210 

based on https://github.com/aeternity/aeternity/pull/4056

AENSv2 in aesophia looks implemented in https://github.com/aeternity/aesophia/pull/426.

This PR is supported by the Æternity Crypto Foundation

### CODE REVIEW

**Comment by hanssv** [comment]
There hasn't been any general demand for such a branch - but I had it locally - it is now pushed to `aesophia_cli`

**Comment by dincho** [comment]
> To test it properly we need a version of `aesophia_cli` that supports `AENSv2`.

to be more specific, a released version after initial/draft tests :)

**Comment by dincho** [comment]
Thanks for the implementation @davidyuk it looks straight forward so far. Thanks to @hanssv for BC :)

**Comment by davidyuk** [comment]
As I understand, bytes(x) have a mandatory prefix of two bytes (FateTag.OBJECT, FateTag.OTYPE_BYTES), but this prefix looks missing in case of decoding AENSv2.name value with DataPr. The first two bytes get lost because of
https://github.com/aeternity/aepp-calldata-js/blob/a70ea77d87fddd73047031dd75835c5e5a21b851/src/Serializers/BytesSerializer.js#L19

The issue https://github.com/aeternity/aesophia/issues/498 looks related. I'm not sure how to proceed here.

**Comment by dincho** [comment]
#258 has been merged, feel free to rebase this PR to get it in as well

**Review by dincho — APPROVED** [review]

**Pull request merged**
