### PR TITLE
Add contact call wrapper

### PR DESCRIPTION
**Pull request by dincho**
Not sure why the tests was passing on master with broken source (missing interface)

### CODE REVIEW

**Comment by marc0olo** [comment]
> Not sure why the tests was passing on master with broken source (missing interface)

I am a bit confused to be honest. I think it is because the we aren't using the Sophia CLI to actually compile the contract. so decoding the calldata is allowed for methods of a contract although they might not be valid.

the intention of the script for making an actual contract call on testnet using the aepp-cli-js now is just for local on-demand tests, right?

**Comment by dincho** [comment]
> > Not sure why the tests was passing on master with broken source (missing interface)
> 
> I am a bit confused to be honest. I think it is because we aren't using the Sophia CLI to actually compile the contract. so decoding the calldata is allowed by the Sophia CLI for methods of a contract although the actual contract might not be valid.
> 
> the intention of the script for making an actual contract call on testnet using the aepp-cli-js now is just for local on-demand tests, right?

We do compile the contract to get the ACI, locally it was failing as expected, still no idea how it passed the CI.

Contracts call wrapper via JS CLI is just a helper that can be used to get some call results for testing as I don’t know a “static” method for that.

**Comment by marc0olo** [comment]
> We do compile the contract to get the ACI, locally it was failing as expected, still no idea how it passed the CI.

I see, very strange. Indeed. I mean this is software, right? 😅 



> Contracts call wrapper via JS CLI is just a helper that can be used to get some call results for testing as I don’t know a “static” method for that.

Alright :-)

**Review by marc0olo — APPROVED** [review]
Looks good to me.

**Review by mradkov — APPROVED** [review]

**Comment by dincho** [comment]
> > We do compile the contract to get the ACI, locally it was failing as expected, still no idea how it passed the CI.
> 
> I see, very strange. Indeed. I mean this is software, right? 😅

@marc0olo I was wrong. see https://github.com/aeternity/aesophia_cli/issues/48

**Pull request merged**
